# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: corepack enable
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - run: yarn install --immutable
    - run: yarn lint
    - run: yarn test
